
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceHealth` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ServiceHealth
 * 
 */
export type ServiceHealthModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceHealthPayload>

export type AggregateServiceHealth = {
  _count: ServiceHealthCountAggregateOutputType | null
  _avg: ServiceHealthAvgAggregateOutputType | null
  _sum: ServiceHealthSumAggregateOutputType | null
  _min: ServiceHealthMinAggregateOutputType | null
  _max: ServiceHealthMaxAggregateOutputType | null
}

export type ServiceHealthAvgAggregateOutputType = {
  service_id: number | null
  last_response_time_ms: number | null
}

export type ServiceHealthSumAggregateOutputType = {
  service_id: number | null
  last_response_time_ms: number | null
}

export type ServiceHealthMinAggregateOutputType = {
  service_id: number | null
  current_status: $Enums.CurrentStatus | null
  last_checked_at: Date | null
  last_response_time_ms: number | null
}

export type ServiceHealthMaxAggregateOutputType = {
  service_id: number | null
  current_status: $Enums.CurrentStatus | null
  last_checked_at: Date | null
  last_response_time_ms: number | null
}

export type ServiceHealthCountAggregateOutputType = {
  service_id: number
  current_status: number
  last_checked_at: number
  last_response_time_ms: number
  _all: number
}


export type ServiceHealthAvgAggregateInputType = {
  service_id?: true
  last_response_time_ms?: true
}

export type ServiceHealthSumAggregateInputType = {
  service_id?: true
  last_response_time_ms?: true
}

export type ServiceHealthMinAggregateInputType = {
  service_id?: true
  current_status?: true
  last_checked_at?: true
  last_response_time_ms?: true
}

export type ServiceHealthMaxAggregateInputType = {
  service_id?: true
  current_status?: true
  last_checked_at?: true
  last_response_time_ms?: true
}

export type ServiceHealthCountAggregateInputType = {
  service_id?: true
  current_status?: true
  last_checked_at?: true
  last_response_time_ms?: true
  _all?: true
}

export type ServiceHealthAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceHealth to aggregate.
   */
  where?: Prisma.ServiceHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceHealths to fetch.
   */
  orderBy?: Prisma.ServiceHealthOrderByWithRelationInput | Prisma.ServiceHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceHealths
  **/
  _count?: true | ServiceHealthCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ServiceHealthAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ServiceHealthSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceHealthMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceHealthMaxAggregateInputType
}

export type GetServiceHealthAggregateType<T extends ServiceHealthAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceHealth]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceHealth[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceHealth[P]>
}




export type ServiceHealthGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceHealthWhereInput
  orderBy?: Prisma.ServiceHealthOrderByWithAggregationInput | Prisma.ServiceHealthOrderByWithAggregationInput[]
  by: Prisma.ServiceHealthScalarFieldEnum[] | Prisma.ServiceHealthScalarFieldEnum
  having?: Prisma.ServiceHealthScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceHealthCountAggregateInputType | true
  _avg?: ServiceHealthAvgAggregateInputType
  _sum?: ServiceHealthSumAggregateInputType
  _min?: ServiceHealthMinAggregateInputType
  _max?: ServiceHealthMaxAggregateInputType
}

export type ServiceHealthGroupByOutputType = {
  service_id: number
  current_status: $Enums.CurrentStatus
  last_checked_at: Date
  last_response_time_ms: number | null
  _count: ServiceHealthCountAggregateOutputType | null
  _avg: ServiceHealthAvgAggregateOutputType | null
  _sum: ServiceHealthSumAggregateOutputType | null
  _min: ServiceHealthMinAggregateOutputType | null
  _max: ServiceHealthMaxAggregateOutputType | null
}

type GetServiceHealthGroupByPayload<T extends ServiceHealthGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceHealthGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceHealthGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceHealthGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceHealthGroupByOutputType[P]>
      }
    >
  >



export type ServiceHealthWhereInput = {
  AND?: Prisma.ServiceHealthWhereInput | Prisma.ServiceHealthWhereInput[]
  OR?: Prisma.ServiceHealthWhereInput[]
  NOT?: Prisma.ServiceHealthWhereInput | Prisma.ServiceHealthWhereInput[]
  service_id?: Prisma.IntFilter<"ServiceHealth"> | number
  current_status?: Prisma.EnumCurrentStatusFilter<"ServiceHealth"> | $Enums.CurrentStatus
  last_checked_at?: Prisma.DateTimeFilter<"ServiceHealth"> | Date | string
  last_response_time_ms?: Prisma.IntNullableFilter<"ServiceHealth"> | number | null
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
}

export type ServiceHealthOrderByWithRelationInput = {
  service_id?: Prisma.SortOrder
  current_status?: Prisma.SortOrder
  last_checked_at?: Prisma.SortOrder
  last_response_time_ms?: Prisma.SortOrderInput | Prisma.SortOrder
  service?: Prisma.ServiceOrderByWithRelationInput
}

export type ServiceHealthWhereUniqueInput = Prisma.AtLeast<{
  service_id?: number
  AND?: Prisma.ServiceHealthWhereInput | Prisma.ServiceHealthWhereInput[]
  OR?: Prisma.ServiceHealthWhereInput[]
  NOT?: Prisma.ServiceHealthWhereInput | Prisma.ServiceHealthWhereInput[]
  current_status?: Prisma.EnumCurrentStatusFilter<"ServiceHealth"> | $Enums.CurrentStatus
  last_checked_at?: Prisma.DateTimeFilter<"ServiceHealth"> | Date | string
  last_response_time_ms?: Prisma.IntNullableFilter<"ServiceHealth"> | number | null
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
}, "service_id">

export type ServiceHealthOrderByWithAggregationInput = {
  service_id?: Prisma.SortOrder
  current_status?: Prisma.SortOrder
  last_checked_at?: Prisma.SortOrder
  last_response_time_ms?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ServiceHealthCountOrderByAggregateInput
  _avg?: Prisma.ServiceHealthAvgOrderByAggregateInput
  _max?: Prisma.ServiceHealthMaxOrderByAggregateInput
  _min?: Prisma.ServiceHealthMinOrderByAggregateInput
  _sum?: Prisma.ServiceHealthSumOrderByAggregateInput
}

export type ServiceHealthScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceHealthScalarWhereWithAggregatesInput | Prisma.ServiceHealthScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceHealthScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceHealthScalarWhereWithAggregatesInput | Prisma.ServiceHealthScalarWhereWithAggregatesInput[]
  service_id?: Prisma.IntWithAggregatesFilter<"ServiceHealth"> | number
  current_status?: Prisma.EnumCurrentStatusWithAggregatesFilter<"ServiceHealth"> | $Enums.CurrentStatus
  last_checked_at?: Prisma.DateTimeWithAggregatesFilter<"ServiceHealth"> | Date | string
  last_response_time_ms?: Prisma.IntNullableWithAggregatesFilter<"ServiceHealth"> | number | null
}

export type ServiceHealthCreateInput = {
  current_status: $Enums.CurrentStatus
  last_checked_at: Date | string
  last_response_time_ms?: number | null
  service: Prisma.ServiceCreateNestedOneWithoutStatusInput
}

export type ServiceHealthUncheckedCreateInput = {
  service_id: number
  current_status: $Enums.CurrentStatus
  last_checked_at: Date | string
  last_response_time_ms?: number | null
}

export type ServiceHealthUpdateInput = {
  current_status?: Prisma.EnumCurrentStatusFieldUpdateOperationsInput | $Enums.CurrentStatus
  last_checked_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  last_response_time_ms?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  service?: Prisma.ServiceUpdateOneRequiredWithoutStatusNestedInput
}

export type ServiceHealthUncheckedUpdateInput = {
  service_id?: Prisma.IntFieldUpdateOperationsInput | number
  current_status?: Prisma.EnumCurrentStatusFieldUpdateOperationsInput | $Enums.CurrentStatus
  last_checked_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  last_response_time_ms?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ServiceHealthCreateManyInput = {
  service_id: number
  current_status: $Enums.CurrentStatus
  last_checked_at: Date | string
  last_response_time_ms?: number | null
}

export type ServiceHealthUpdateManyMutationInput = {
  current_status?: Prisma.EnumCurrentStatusFieldUpdateOperationsInput | $Enums.CurrentStatus
  last_checked_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  last_response_time_ms?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ServiceHealthUncheckedUpdateManyInput = {
  service_id?: Prisma.IntFieldUpdateOperationsInput | number
  current_status?: Prisma.EnumCurrentStatusFieldUpdateOperationsInput | $Enums.CurrentStatus
  last_checked_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  last_response_time_ms?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ServiceHealthNullableScalarRelationFilter = {
  is?: Prisma.ServiceHealthWhereInput | null
  isNot?: Prisma.ServiceHealthWhereInput | null
}

export type ServiceHealthCountOrderByAggregateInput = {
  service_id?: Prisma.SortOrder
  current_status?: Prisma.SortOrder
  last_checked_at?: Prisma.SortOrder
  last_response_time_ms?: Prisma.SortOrder
}

export type ServiceHealthAvgOrderByAggregateInput = {
  service_id?: Prisma.SortOrder
  last_response_time_ms?: Prisma.SortOrder
}

export type ServiceHealthMaxOrderByAggregateInput = {
  service_id?: Prisma.SortOrder
  current_status?: Prisma.SortOrder
  last_checked_at?: Prisma.SortOrder
  last_response_time_ms?: Prisma.SortOrder
}

export type ServiceHealthMinOrderByAggregateInput = {
  service_id?: Prisma.SortOrder
  current_status?: Prisma.SortOrder
  last_checked_at?: Prisma.SortOrder
  last_response_time_ms?: Prisma.SortOrder
}

export type ServiceHealthSumOrderByAggregateInput = {
  service_id?: Prisma.SortOrder
  last_response_time_ms?: Prisma.SortOrder
}

export type ServiceHealthCreateNestedOneWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.ServiceHealthCreateWithoutServiceInput, Prisma.ServiceHealthUncheckedCreateWithoutServiceInput>
  connectOrCreate?: Prisma.ServiceHealthCreateOrConnectWithoutServiceInput
  connect?: Prisma.ServiceHealthWhereUniqueInput
}

export type ServiceHealthUncheckedCreateNestedOneWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.ServiceHealthCreateWithoutServiceInput, Prisma.ServiceHealthUncheckedCreateWithoutServiceInput>
  connectOrCreate?: Prisma.ServiceHealthCreateOrConnectWithoutServiceInput
  connect?: Prisma.ServiceHealthWhereUniqueInput
}

export type ServiceHealthUpdateOneWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceHealthCreateWithoutServiceInput, Prisma.ServiceHealthUncheckedCreateWithoutServiceInput>
  connectOrCreate?: Prisma.ServiceHealthCreateOrConnectWithoutServiceInput
  upsert?: Prisma.ServiceHealthUpsertWithoutServiceInput
  disconnect?: Prisma.ServiceHealthWhereInput | boolean
  delete?: Prisma.ServiceHealthWhereInput | boolean
  connect?: Prisma.ServiceHealthWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceHealthUpdateToOneWithWhereWithoutServiceInput, Prisma.ServiceHealthUpdateWithoutServiceInput>, Prisma.ServiceHealthUncheckedUpdateWithoutServiceInput>
}

export type ServiceHealthUncheckedUpdateOneWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceHealthCreateWithoutServiceInput, Prisma.ServiceHealthUncheckedCreateWithoutServiceInput>
  connectOrCreate?: Prisma.ServiceHealthCreateOrConnectWithoutServiceInput
  upsert?: Prisma.ServiceHealthUpsertWithoutServiceInput
  disconnect?: Prisma.ServiceHealthWhereInput | boolean
  delete?: Prisma.ServiceHealthWhereInput | boolean
  connect?: Prisma.ServiceHealthWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceHealthUpdateToOneWithWhereWithoutServiceInput, Prisma.ServiceHealthUpdateWithoutServiceInput>, Prisma.ServiceHealthUncheckedUpdateWithoutServiceInput>
}

export type EnumCurrentStatusFieldUpdateOperationsInput = {
  set?: $Enums.CurrentStatus
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ServiceHealthCreateWithoutServiceInput = {
  current_status: $Enums.CurrentStatus
  last_checked_at: Date | string
  last_response_time_ms?: number | null
}

export type ServiceHealthUncheckedCreateWithoutServiceInput = {
  current_status: $Enums.CurrentStatus
  last_checked_at: Date | string
  last_response_time_ms?: number | null
}

export type ServiceHealthCreateOrConnectWithoutServiceInput = {
  where: Prisma.ServiceHealthWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceHealthCreateWithoutServiceInput, Prisma.ServiceHealthUncheckedCreateWithoutServiceInput>
}

export type ServiceHealthUpsertWithoutServiceInput = {
  update: Prisma.XOR<Prisma.ServiceHealthUpdateWithoutServiceInput, Prisma.ServiceHealthUncheckedUpdateWithoutServiceInput>
  create: Prisma.XOR<Prisma.ServiceHealthCreateWithoutServiceInput, Prisma.ServiceHealthUncheckedCreateWithoutServiceInput>
  where?: Prisma.ServiceHealthWhereInput
}

export type ServiceHealthUpdateToOneWithWhereWithoutServiceInput = {
  where?: Prisma.ServiceHealthWhereInput
  data: Prisma.XOR<Prisma.ServiceHealthUpdateWithoutServiceInput, Prisma.ServiceHealthUncheckedUpdateWithoutServiceInput>
}

export type ServiceHealthUpdateWithoutServiceInput = {
  current_status?: Prisma.EnumCurrentStatusFieldUpdateOperationsInput | $Enums.CurrentStatus
  last_checked_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  last_response_time_ms?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ServiceHealthUncheckedUpdateWithoutServiceInput = {
  current_status?: Prisma.EnumCurrentStatusFieldUpdateOperationsInput | $Enums.CurrentStatus
  last_checked_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  last_response_time_ms?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type ServiceHealthSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  service_id?: boolean
  current_status?: boolean
  last_checked_at?: boolean
  last_response_time_ms?: boolean
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceHealth"]>

export type ServiceHealthSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  service_id?: boolean
  current_status?: boolean
  last_checked_at?: boolean
  last_response_time_ms?: boolean
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceHealth"]>

export type ServiceHealthSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  service_id?: boolean
  current_status?: boolean
  last_checked_at?: boolean
  last_response_time_ms?: boolean
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceHealth"]>

export type ServiceHealthSelectScalar = {
  service_id?: boolean
  current_status?: boolean
  last_checked_at?: boolean
  last_response_time_ms?: boolean
}

export type ServiceHealthOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"service_id" | "current_status" | "last_checked_at" | "last_response_time_ms", ExtArgs["result"]["serviceHealth"]>
export type ServiceHealthInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}
export type ServiceHealthIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}
export type ServiceHealthIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}

export type $ServiceHealthPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceHealth"
  objects: {
    service: Prisma.$ServicePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    service_id: number
    current_status: $Enums.CurrentStatus
    last_checked_at: Date
    last_response_time_ms: number | null
  }, ExtArgs["result"]["serviceHealth"]>
  composites: {}
}

export type ServiceHealthGetPayload<S extends boolean | null | undefined | ServiceHealthDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload, S>

export type ServiceHealthCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceHealthFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceHealthCountAggregateInputType | true
  }

export interface ServiceHealthDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceHealth'], meta: { name: 'ServiceHealth' } }
  /**
   * Find zero or one ServiceHealth that matches the filter.
   * @param {ServiceHealthFindUniqueArgs} args - Arguments to find a ServiceHealth
   * @example
   * // Get one ServiceHealth
   * const serviceHealth = await prisma.serviceHealth.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceHealthFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceHealthFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceHealthClient<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceHealth that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceHealthFindUniqueOrThrowArgs} args - Arguments to find a ServiceHealth
   * @example
   * // Get one ServiceHealth
   * const serviceHealth = await prisma.serviceHealth.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceHealthFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceHealthFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceHealthClient<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceHealth that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceHealthFindFirstArgs} args - Arguments to find a ServiceHealth
   * @example
   * // Get one ServiceHealth
   * const serviceHealth = await prisma.serviceHealth.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceHealthFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceHealthFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceHealthClient<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceHealth that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceHealthFindFirstOrThrowArgs} args - Arguments to find a ServiceHealth
   * @example
   * // Get one ServiceHealth
   * const serviceHealth = await prisma.serviceHealth.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceHealthFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceHealthFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceHealthClient<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceHealths that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceHealthFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceHealths
   * const serviceHealths = await prisma.serviceHealth.findMany()
   * 
   * // Get first 10 ServiceHealths
   * const serviceHealths = await prisma.serviceHealth.findMany({ take: 10 })
   * 
   * // Only select the `service_id`
   * const serviceHealthWithService_idOnly = await prisma.serviceHealth.findMany({ select: { service_id: true } })
   * 
   */
  findMany<T extends ServiceHealthFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceHealthFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceHealth.
   * @param {ServiceHealthCreateArgs} args - Arguments to create a ServiceHealth.
   * @example
   * // Create one ServiceHealth
   * const ServiceHealth = await prisma.serviceHealth.create({
   *   data: {
   *     // ... data to create a ServiceHealth
   *   }
   * })
   * 
   */
  create<T extends ServiceHealthCreateArgs>(args: Prisma.SelectSubset<T, ServiceHealthCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceHealthClient<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceHealths.
   * @param {ServiceHealthCreateManyArgs} args - Arguments to create many ServiceHealths.
   * @example
   * // Create many ServiceHealths
   * const serviceHealth = await prisma.serviceHealth.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceHealthCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceHealthCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServiceHealths and returns the data saved in the database.
   * @param {ServiceHealthCreateManyAndReturnArgs} args - Arguments to create many ServiceHealths.
   * @example
   * // Create many ServiceHealths
   * const serviceHealth = await prisma.serviceHealth.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServiceHealths and only return the `service_id`
   * const serviceHealthWithService_idOnly = await prisma.serviceHealth.createManyAndReturn({
   *   select: { service_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ServiceHealthCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ServiceHealthCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServiceHealth.
   * @param {ServiceHealthDeleteArgs} args - Arguments to delete one ServiceHealth.
   * @example
   * // Delete one ServiceHealth
   * const ServiceHealth = await prisma.serviceHealth.delete({
   *   where: {
   *     // ... filter to delete one ServiceHealth
   *   }
   * })
   * 
   */
  delete<T extends ServiceHealthDeleteArgs>(args: Prisma.SelectSubset<T, ServiceHealthDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceHealthClient<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceHealth.
   * @param {ServiceHealthUpdateArgs} args - Arguments to update one ServiceHealth.
   * @example
   * // Update one ServiceHealth
   * const serviceHealth = await prisma.serviceHealth.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceHealthUpdateArgs>(args: Prisma.SelectSubset<T, ServiceHealthUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceHealthClient<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceHealths.
   * @param {ServiceHealthDeleteManyArgs} args - Arguments to filter ServiceHealths to delete.
   * @example
   * // Delete a few ServiceHealths
   * const { count } = await prisma.serviceHealth.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceHealthDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceHealthDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceHealths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceHealthUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceHealths
   * const serviceHealth = await prisma.serviceHealth.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceHealthUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceHealthUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceHealths and returns the data updated in the database.
   * @param {ServiceHealthUpdateManyAndReturnArgs} args - Arguments to update many ServiceHealths.
   * @example
   * // Update many ServiceHealths
   * const serviceHealth = await prisma.serviceHealth.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServiceHealths and only return the `service_id`
   * const serviceHealthWithService_idOnly = await prisma.serviceHealth.updateManyAndReturn({
   *   select: { service_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ServiceHealthUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ServiceHealthUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServiceHealth.
   * @param {ServiceHealthUpsertArgs} args - Arguments to update or create a ServiceHealth.
   * @example
   * // Update or create a ServiceHealth
   * const serviceHealth = await prisma.serviceHealth.upsert({
   *   create: {
   *     // ... data to create a ServiceHealth
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceHealth we want to update
   *   }
   * })
   */
  upsert<T extends ServiceHealthUpsertArgs>(args: Prisma.SelectSubset<T, ServiceHealthUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceHealthClient<runtime.Types.Result.GetResult<Prisma.$ServiceHealthPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceHealths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceHealthCountArgs} args - Arguments to filter ServiceHealths to count.
   * @example
   * // Count the number of ServiceHealths
   * const count = await prisma.serviceHealth.count({
   *   where: {
   *     // ... the filter for the ServiceHealths we want to count
   *   }
   * })
  **/
  count<T extends ServiceHealthCountArgs>(
    args?: Prisma.Subset<T, ServiceHealthCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceHealthCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceHealth.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceHealthAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceHealthAggregateArgs>(args: Prisma.Subset<T, ServiceHealthAggregateArgs>): Prisma.PrismaPromise<GetServiceHealthAggregateType<T>>

  /**
   * Group by ServiceHealth.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceHealthGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceHealthGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceHealthGroupByArgs['orderBy'] }
      : { orderBy?: ServiceHealthGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceHealthGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceHealthGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceHealth model
 */
readonly fields: ServiceHealthFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceHealth.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceHealthClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  service<T extends Prisma.ServiceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceHealth model
 */
export interface ServiceHealthFieldRefs {
  readonly service_id: Prisma.FieldRef<"ServiceHealth", 'Int'>
  readonly current_status: Prisma.FieldRef<"ServiceHealth", 'CurrentStatus'>
  readonly last_checked_at: Prisma.FieldRef<"ServiceHealth", 'DateTime'>
  readonly last_response_time_ms: Prisma.FieldRef<"ServiceHealth", 'Int'>
}
    

// Custom InputTypes
/**
 * ServiceHealth findUnique
 */
export type ServiceHealthFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
  /**
   * Filter, which ServiceHealth to fetch.
   */
  where: Prisma.ServiceHealthWhereUniqueInput
}

/**
 * ServiceHealth findUniqueOrThrow
 */
export type ServiceHealthFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
  /**
   * Filter, which ServiceHealth to fetch.
   */
  where: Prisma.ServiceHealthWhereUniqueInput
}

/**
 * ServiceHealth findFirst
 */
export type ServiceHealthFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
  /**
   * Filter, which ServiceHealth to fetch.
   */
  where?: Prisma.ServiceHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceHealths to fetch.
   */
  orderBy?: Prisma.ServiceHealthOrderByWithRelationInput | Prisma.ServiceHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceHealths.
   */
  cursor?: Prisma.ServiceHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceHealths.
   */
  distinct?: Prisma.ServiceHealthScalarFieldEnum | Prisma.ServiceHealthScalarFieldEnum[]
}

/**
 * ServiceHealth findFirstOrThrow
 */
export type ServiceHealthFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
  /**
   * Filter, which ServiceHealth to fetch.
   */
  where?: Prisma.ServiceHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceHealths to fetch.
   */
  orderBy?: Prisma.ServiceHealthOrderByWithRelationInput | Prisma.ServiceHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceHealths.
   */
  cursor?: Prisma.ServiceHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceHealths.
   */
  distinct?: Prisma.ServiceHealthScalarFieldEnum | Prisma.ServiceHealthScalarFieldEnum[]
}

/**
 * ServiceHealth findMany
 */
export type ServiceHealthFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
  /**
   * Filter, which ServiceHealths to fetch.
   */
  where?: Prisma.ServiceHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceHealths to fetch.
   */
  orderBy?: Prisma.ServiceHealthOrderByWithRelationInput | Prisma.ServiceHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceHealths.
   */
  cursor?: Prisma.ServiceHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceHealths.
   */
  skip?: number
  distinct?: Prisma.ServiceHealthScalarFieldEnum | Prisma.ServiceHealthScalarFieldEnum[]
}

/**
 * ServiceHealth create
 */
export type ServiceHealthCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceHealth.
   */
  data: Prisma.XOR<Prisma.ServiceHealthCreateInput, Prisma.ServiceHealthUncheckedCreateInput>
}

/**
 * ServiceHealth createMany
 */
export type ServiceHealthCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceHealths.
   */
  data: Prisma.ServiceHealthCreateManyInput | Prisma.ServiceHealthCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServiceHealth createManyAndReturn
 */
export type ServiceHealthCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * The data used to create many ServiceHealths.
   */
  data: Prisma.ServiceHealthCreateManyInput | Prisma.ServiceHealthCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceHealth update
 */
export type ServiceHealthUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceHealth.
   */
  data: Prisma.XOR<Prisma.ServiceHealthUpdateInput, Prisma.ServiceHealthUncheckedUpdateInput>
  /**
   * Choose, which ServiceHealth to update.
   */
  where: Prisma.ServiceHealthWhereUniqueInput
}

/**
 * ServiceHealth updateMany
 */
export type ServiceHealthUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceHealths.
   */
  data: Prisma.XOR<Prisma.ServiceHealthUpdateManyMutationInput, Prisma.ServiceHealthUncheckedUpdateManyInput>
  /**
   * Filter which ServiceHealths to update
   */
  where?: Prisma.ServiceHealthWhereInput
  /**
   * Limit how many ServiceHealths to update.
   */
  limit?: number
}

/**
 * ServiceHealth updateManyAndReturn
 */
export type ServiceHealthUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * The data used to update ServiceHealths.
   */
  data: Prisma.XOR<Prisma.ServiceHealthUpdateManyMutationInput, Prisma.ServiceHealthUncheckedUpdateManyInput>
  /**
   * Filter which ServiceHealths to update
   */
  where?: Prisma.ServiceHealthWhereInput
  /**
   * Limit how many ServiceHealths to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceHealth upsert
 */
export type ServiceHealthUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceHealth to update in case it exists.
   */
  where: Prisma.ServiceHealthWhereUniqueInput
  /**
   * In case the ServiceHealth found by the `where` argument doesn't exist, create a new ServiceHealth with this data.
   */
  create: Prisma.XOR<Prisma.ServiceHealthCreateInput, Prisma.ServiceHealthUncheckedCreateInput>
  /**
   * In case the ServiceHealth was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceHealthUpdateInput, Prisma.ServiceHealthUncheckedUpdateInput>
}

/**
 * ServiceHealth delete
 */
export type ServiceHealthDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
  /**
   * Filter which ServiceHealth to delete.
   */
  where: Prisma.ServiceHealthWhereUniqueInput
}

/**
 * ServiceHealth deleteMany
 */
export type ServiceHealthDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceHealths to delete
   */
  where?: Prisma.ServiceHealthWhereInput
  /**
   * Limit how many ServiceHealths to delete.
   */
  limit?: number
}

/**
 * ServiceHealth without action
 */
export type ServiceHealthDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceHealth
   */
  select?: Prisma.ServiceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceHealth
   */
  omit?: Prisma.ServiceHealthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceHealthInclude<ExtArgs> | null
}
