
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Environment = {
  DEV: 'DEV',
  STATINGS: 'STATINGS',
  PROD: 'PROD'
} as const

export type Environment = (typeof Environment)[keyof typeof Environment]


export const CurrentStatus = {
  ONLINE: 'ONLINE',
  INSTAVEL: 'INSTAVEL',
  OFFLINE: 'OFFLINE'
} as const

export type CurrentStatus = (typeof CurrentStatus)[keyof typeof CurrentStatus]


export const IncidentStatus = {
  INSTAVEL: 'INSTAVEL',
  OFFLINE: 'OFFLINE'
} as const

export type IncidentStatus = (typeof IncidentStatus)[keyof typeof IncidentStatus]
